### ISSUE TITLE
New feature: NDJSON and CSV payloads

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1142]
v0.23 will accept data payloads in NDJSON and CSV formats, in addition to JSON.

Tasks:
- [ ] Update POST/PUT cURL code samples
  - [ ] Add content header: `-H 'Content-Type: application/json'`
  - [ ] Replace `--data` with `--data-binary`
- [ ] Update `/faq`: mention new payload formats as possible fixes to these issues:
  - [ ] Update question under header: `Why does MeiliSearch crash when I try to add documents?`
  - [ ] Update question under header: `How can I speed up indexation when adding new documents?`
- [ ] Update possible mentions to JSON payloads so they either mention all three formats or none. _Note: this list is based off a quick `ack` search and whoever executes this task should review it._
  - [ ] reference/api/README.md L#19, 17, 52, 69
  - [ ] learn/core_concepts/documents.md L#23, 16, 55, 159
  - [ ] create/how_to/updating.md L#256
  - [ ] errors.yaml L#44
  - [ ] learn/getting_started/quick_start.md: L#46
  - [ ] reference/api/documents.md
  - [ ] reference/features/configuration.md L#233
  - [ ] reference/features/synonyms.md L#39, 59
  - [ ] reference/under_the_hood/datatypes.md 104
  - [ ] resources/faq.md 75
