### ISSUE TITLE
Specify content headers in all PUT/POST code samples

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1146]
v0.23 will allow payloads in formats other than JSON. For that reason, specifying the content header will be mandatory.

# Tasks
- [x] Identify all code sample instances that need updating and list them here
- [x] Add content header: `-H 'Content-Type: application/json'`
- [x] Replace `--data` with `--data-binary`

---

## Reference material
- Issue on core: https://github.com/meilisearch/MeiliSearch/issues/1665
