### ISSUE TITLE
v0.25: Task API

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1190]
The Update API is used to handle asynchronous processes throughout MeiliSearch. It is particularly common when dealing with an index's settings or adding new documents — since both operations can take a significant amount of time, they are processed separately and leave the main thread free for other tasks.

This API's name is a common source of confusion, since a user can update an index's key, its documents, or just use the word to refer to changing something.

For this reason, v0.25 renames Updates to Task. Full information can be found on the spec linked below.

---

## Tasks

- [x] Update API reference (all routes)
- [x] Update `/learn/asynchronous_updates.md`
- [x] Search for other mentions of `Update` throughout the documentation and update them when necessary
- [x] Search for `Update` responses (e.g. https://docs.meilisearch.com/create/how_to/updating.html)
- [x] Check whether the `updateId` object returned when triggering an async update remains the same. Very likely it changes to something like `taskId`. See above example for an example of `updateId`
- [x] Update `update` objects so they match the `task` schema
- [x] Add new error to `errors.yaml`: `task_not_found`
- [x] Update configuration option: `--max-udb-size` to `--max-task-db-size` (don't forget its corresponding env var)
- [x] Update telemetry page with new collected data
- [x] Confirm with product/core that none of these changes influence the Dump API

---

## Reference
- https://github.com/meilisearch/specifications/blob/develop/text/0060-refashion-updates-apis.md
- https://github.com/meilisearch/MeiliSearch/issues/1780

**Comment by maryamsulemani97** [comment]
@guimachiavelli @dichotommy 
For [this](https://docs.meilisearch.com/learn/advanced/asynchronous_updates.html#terminate-meilisearch-while-a-task-is-being-processed) section of the Asynchronous updates article:
- the term "task" refers to any task and not just updates
- the term "update task" refers to what is now "task"
What would be a better alternative for the old "task" term? "Process" or "Operation"

**Comment by dichotommy** [comment]
> the term "task" refers to any task and not just updates
> the term "update task" refers to what is now "task"

I'm not sure that this was an intentional distinction, but I think the way you've defined it is useful nonetheless.

>   What would be a better alternative for the old "task" term? "Process" or "Operation"

I like "asynchronous operation" as an umbrella term. To my knowledge, the only asynchronous operation we have that isn't a "task" is dump creation.
