### ISSUE TITLE
v0.25: API Keys: Authorization guide update

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1284]
The new API Keys spec invalidates about 90%-95% of `reference/features/authentication.md`. We need to fully rewrite this guide so users know how to properly secure their instances. 

We also decided to move away from using authentication, as it is not the most accurate term for describing how keys are used in MeiliSearch.

---

## Tasks
- [ ] Rename `reference/features/authentication.md` to `reference/features/security.md` 
- [ ] Rewrite security (previously authentication) guide:
  - [ ] describe two types of keys, `main` and `API` and their uses
  - [ ] how to activate authentication and when it is mandatory
  - [ ] communicating with a protected instance with an API key
  - [ ] managing API keys with the `main` key and the `/keys` endpoint (should cover creation, update, deletion, and expiry)
  - [ ] best practices regarding expiry dates (a key can be explicitly set to never expire, but this can be a security issue)
- [ ] Draft a mini migration guide in case updating to v0.25 can lead to auth issues and loss of access to protected instances

---

## References
- spec PR: https://github.com/meilisearch/specifications/pull/85

**Comment by dichotommy** [comment]
Note that the name of the `main` key is still [a subject of debate](https://github.com/meilisearch/specifications/pull/85#issuecomment-973013863).
