### ISSUE TITLE
v0.25: API keys: Guides, settings, options

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1287]
Besides requiring rewriting significant sections of the Security/Authentication guide and the API reference, the new API keys has an effect on many other articles that mention things such as the `master` key.

These include any guides on deploying MeiliSearch in production environments or configuring cloud services, as well as configuration options references.

--- 

## Tasks

- [ ] Search for mentions of previous Authentication system since it is possible the current list is not exhaustive
- [x] reference/features/configuration.md#environment: update references to keys (at a minimum remove references to the `master` key
- [x] `reference/features/configuration.md#master-key`: rewrite
- [x] Update create/how_to/running_production
- [x] create/how_to/postman_collection (not sure about this one)
- [x] create/how_to/aws
- [x] create/how_to/gcp
- [x] create/how_to/digitalocean_droplet
- [x] create/how_to/qovery (this guide is out of date and only compatible with qovery v1.0)
- [x] create/how_to/search_bar_for_docs
- [x] Add a mention to fine-grained API key management to learn/what_is_meilisearch/features

## Reference
- spec PR: https://github.com/meilisearch/specifications/pull/85

**Comment by guimachiavelli** [comment]
FYI, the spec has been updated. `main` is once again called `master`, so some of the articles in the task list might not need  updates.

**Comment by guimachiavelli** [comment]
Another update: changing the `master` key will reset all other other keys: https://github.com/meilisearch/specifications/pull/85#issuecomment-979323179
