### ISSUE TITLE
v0.26: New feature: Tenant tokens

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1416]
## Summary
The main use-case for tenant tokens is to enforce restrictions based on user permissions. For instance, when user "Gui"  searches their medical records in database, they should only see their own documents and never those belonging to users "Maryam" or "Tommy".

Tenant token generation process in a sample medical records database:
1. End-user logs in an application;
2. When the log in is successful, the application creates a set of restrictions in the back-end. These restrictions are essentially a set of filters that can be configured both for a whole instance or to some of the indexes in the instance. They can also include an expiry date;
3. Via either an SDK or custom code, the application then generates a token by serialising the restrictions and an API key with access to the search route;
4. The token is sent to the front-end, where it will be used to search instead of e.g. the Default Search API Key. The Tenant Token effectively replaces the API key for logged in users;
5. Any searches made using a Tenant Token will always include the set of filters configured in its restrictions. For instance, if a Tenant Token was created using the filter `user_id == 1`, a search will only return documents containing an `user_id` attribute with a matching value. This is of course on top of any other filters that might have been set on the front-end;
6. Restrictions can chain several filters. For instance, a Tenant Token might return only documents with a `user_id` of `1` **and** with a `published` value of true—meaning, users will only see documents that belong to them and which have been published.

Note: **API keys remain a valid way of making search requests.** For example, an application might use Tenant Tokens for logged-in users and the Default Search API Key for the others. In such a setup, it is likely the Default Search API Key will only have access to indexes that e.g. do not contain sensitive information.

## Code samples

Code samples for this guide will be different than what we're used to. Since tenant tokens seamlessly replace API keys and require no configuration, the only code required by tenant tokens is the actual generation of the token itself (consult the spec's JS sample for reference). This means it makes no sense to create a default `curl` sample.

Following @gmourier's recommendation, examples should use the medical records scenario like the guide for API keys (aka `The Patient Medical Records Saga`).

## Tasks
- [x] Create new top-level section on "Learn" sidebar menu named "Security and permissions"
- [x] Rename current "Security and permissions" guide to "Master and API keys" (or something better than that)
- [x] Write new "Tenant tokens" guide:
  - [x] Code samples: consult @meilisearch/integration-team (especially @bidoubiwa). Should we create a simple JS/pseudocode sample to serve as a basis for SDK-specific samples? What would they appreciate, as developers, to find in this guide?
  - [x] Mention that Tenant tokens can be used together with regular API keys

## References
Spec: https://github.com/meilisearch/specifications/pull/89
Issue on core: https://github.com/meilisearch/MeiliSearch/issues/1991
Issue on integrations describing SDK signatures: https://github.com/meilisearch/integration-guides/issues/181#issuecomment-1043304750
Discussion: https://github.com/meilisearch/documentation/discussions/1365#discussioncomment-1955091

**Comment by curquiza** [comment]
> Code samples: consult https://github.com/orgs/meilisearch/teams/integration-team (especially @bidoubiwa). Should we create a simple JS/pseudocode sample to serve as a basis for SDK-specific samples? What would they appreciate, as developers, to find in this guide?

Should also put @brunoocasali in the loop regarding the code samples you want to add, since he does the sync with the whole team regarding what should be integrated to SDKs for v0.26.0 :)

**Comment by bidoubiwa** [comment]
Should we also mention that tenant tokens can be used to filter on other criteria than the user itself? 
For example, if I want people to only access movies that are after 2010 I could add a filter inside the token with the following:

```js
{
   searchRules: {
     "movies": {
         filter: "release_date > 2010"
      }
   }
}
```

It is just a suggestion of course! As tokens have multiple purposes.

> Should we create a simple JS/pseudocode sample to serve as a basis for SDK-specific samples? What would they appreciate, as developers, to find in this guide?

What code would you like to write for this guide ?: 
- How to create a JWT/Tenant Token from scratch (64 encoding, hashing etc..)
- How to create a JWT/Tenant Token using the most notorious libraries: for example [node-jsonwebtokens](https://github.com/auth0/node-jsonwebtoken) (~15k stars)
- How to create JWT/Tenant Token using a helper function we will add in the SDK (While mentioning this function I think it is best to make a guide that is not dependent on a meilisearch SDK)

Since javascript is common it could be an idea, PHP as well. It is always possible to create a tab like the one in [the installation guide](https://docs.meilisearch.com/learn/getting_started/installation.html#download-and-launch) with different tabs of different popular languages. See example in the [documentation of google](https://cloud.google.com/iot/docs/how-tos/credentials/jwts) on the same topic.

**Comment by gmourier** [comment]
> Should we also mention that tenant tokens can be used to filter on other criteria than the user itself?

From the feedback I've gathered, it's a nice-to-have that is **not the main need** of users.

However, I agree that it is really interesting to mention it somewhere. We could have a page dedicated to the customization of the search results per end-user (Dedicated exclusively to the tenant token feature for now), which talks about the security aspect but also about the personalization/contextualization aspect.

I imagine that a user will search for something like this and come across this guide:

- How to have a multi-tenant index?
- How to customize the search results for a user?
- How do I make sure a user only sees documents that belong to them?

**Comment by guimachiavelli** [comment]
> What code would you like to write for this guide?
> How to create a JWT/Tenant Token from scratch (64 encoding, hashing etc..)
> How to create a JWT/Tenant Token using the most notorious libraries: for example [node-jsonwebtokens](https://github.com/auth0/node-jsonwebtoken) (~15k stars)
> How to create JWT/Tenant Token using a helper function we will add in the SDK (While mentioning this function I think it is best to make a guide that is not dependent on a meilisearch SDK in this particular case)

We still do not have an outline ready for this, but I was thinking of two sections for this guide:

1. one that's more plug-n-play and focusses on our SDKs. The goal would be to give users the fastest route to getting tenant tokens online;
2. one that's bit more DYI and shows people how to do it without our SDKs. Possibly both completely vanilla and using a third-party library like the one linked by @bidoubiwa. This one would be to give devs who prefer to avoid managing third-party dependencies (I'm actually in that group 😅).

Section #1 is higher-priority since it aligns with the docs goal of being accessible to new users.

**Comment by alallema** [comment]
> We still do not have an outline ready for this, but I was thinking of two sections for this guide:
> 
> 1. one that's more plug-n-play and focusses on our SDKs. The goal would be to give users the fastest route to getting tenant tokens online;
> 2. one that's bit more DYI and shows people how to do it without our SDKs. Possibly both completely vanilla and using a third-party library like the one linked by @bidoubiwa. This one would be to give devs who prefer to avoid managing third-party dependencies (I'm actually in that group 😅).
> 
> Section #1 is higher-priority since it aligns with the docs goal of being accessible to new users.

Something like for the [tasks](https://docs.meilisearch.com/reference/api/tasks.html#tasks) and [asynchronous-operations](https://docs.meilisearch.com/learn/advanced/asynchronous_operations.html#asynchronous-operations) in advanced topics? I like this idea ⭐

**Comment by bidoubiwa** [comment]
In this case some further sync will be needed on the date of the release: 

- Every SDK will have to be ready to release
- Every SDK will need to have the helper function added

@brunoocasali @curquiza what do you think?

**Comment by guimachiavelli** [comment]
ah, my apologies, that's a very good point. I hadn't factored in the amount of effort this could require for the @meilisearch/integration-team. 

If being synced with release is not feasible for you, we will of course adapt and only implement the SDK-focussed section after we're all ready.

**Comment by curquiza** [comment]
We discussed this during our sync meeting with @guimachiavelli and @brunoocasali. Not all the SDKs need to be ready to be merged on the hour of the release. I mean, we don't need to merge instantly all the SDKs.
I would say, the more important ones should be ready to be merged (so reviewed and approved in advance) the day of the release: PHP, JS, and Python SDKs I would say. The guide will be already relevant with the Python, JS, and PHP examples, no need to have all of them. The other one will come the same day or the following day, but not necessarily the same hour.

The issue is the following: the SDK branches cannot be merged without the `latest` docker image to be released (because used in our CIs), and this image takes a lot of time to be built (around 1h15). Regarding this, we have two solutions after I push the "release Meilisearch v0.26.0" button.
- the docs deploy immediately the new documentation without waiting for the SDKs. Once the SDKs branches have been merged, the integration team let the docs team know, and the docs team deploys again the documentation. Consequences: the docs are immediately available for v0.26.0, but the tenant token guide is "broken" for 1h30.
- the docs team waits for the SDKs to merge their branches before deploying the documentation. Consequences: during 1h, the documentation still how the v0.25.0 documentation, and not v0.26.0 one. However, once the documentation is deployed, the tenant token guide is not broken

**Comment by guimachiavelli** [comment]
I guess an important part of this process is: who, if anyone, gets notified about a new Meilisearch release once you push that button? Everyone who starred the repo? Only people who `watch` it? Neither and everyone finds out about new versions via social media and etc?

Delaying doc release could be ok if we can have some certainty relatively few people will learn about the new version after the SDK deployment window.

@meilisearch/docs-team: anyone else want to give their opinion?

**Comment by curquiza** [comment]
When I push the release button, only people watching the repo are informed. So, at maximum 208 persons 

<img width="272" alt="Capture d’écran 2022-02-16 à 16 17 38" src="https://user-images.githubusercontent.com/20380692/154295653-a27f127a-d4ea-4d08-868c-15020046fd9a.png">

I'll immediately inform the dev rel team they should NOT communicate about the release until the documentation is ready then :)
