### ISSUE TITLE
v0.26: Instance options: flags must not be followed by a value

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1418]
## Summary
Currently, all CLI options require a value. This is true even for options which don't have any logical value, so `--no-analytics` must be written as `--no-analytics=true`. Confusingly, the value after these options does not matter, so both `--no-analytics=true` and `--no-analytics=false` will disable analytics.

v0.26 will fix this in two ways:

- 7 CLI options are now flags, meaning, they do not take a value. Assigning a value to flag will cause Meilisearch to throw an error;
- Environment variables accept `n`, `no`, `f`, `false`, `off`,  and `0` as false literals. Meaning, no `MEILI_NO_ANALYTICS=false` will not disable analytics.

The affected instance options are:

- `--no-analytics`
- `--schedule-snapshot`
- `--ignore-missing-snapshot`
- `--ignore-snapshot-if-db-exists`
- `--ssl-require-auth`
- `--ssl-resumption`
- `--ssl-tickets`

## Tasks
- [ ] Update Instance options guide Usage section
- [ ] Update rest of Instance options guide where necessary
- [ ] Optional: add information regarding error when providing a value to a flag
- [ ] Scan the rest of the docs for mentions of these options (e.g. `--no-analytics` in the telemetry page, etc). Dedicate special attention to examples.

## References
Issue on core: https://github.com/meilisearch/MeiliSearch/issues/2097
Discussion: https://github.com/meilisearch/documentation/discussions/1365#discussioncomment-2045001
Related issue: #1420
