### ISSUE TITLE
v0.26: Importing dumps into instances with existing DBs returns an error

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1420]
## Summary
Currently, importing a dump into an instance with an existing database will cause the import process to silently fail.

With v0.26, doing so will throw an error and interrupt the `meilisearch` process. 

A user can prevent the error and interrupt by using the new `--ignore-dump-if-db-exists` CLI flag. This will cause Meilisearch to ignore the dump and launch as usual with the existing databse.

A user can also use the `--ignore-missing-dump` CLI flag to prevent Meilisearch from throwing an error when the path supplied to `--import-dump` does not contain a valid dump file.

## Tasks
- [ ] Update the instance options guide to reflect the new behaviour
- [ ] Add `--ignore-dump-if-db-exists` to instance options guide
- [ ] Add `--ignore-missing-dump` to instance options guide

## References
Spec: https://github.com/meilisearch/specifications/pull/105/files
Issue on core: https://github.com/meilisearch/MeiliSearch/issues/2087
Discussion: https://github.com/meilisearch/documentation/discussions/1365#discussioncomment-2053017
