### ISSUE TITLE
v0.26: Rebranded search preview

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1421]
## Summary
Meilisearch revealed its new brand on January 2022. The search preview will receive a fresh coat of pain and a new logo, but should remain unchanged otherwise.

## Tasks
Update the following media files
- [ ] aws/enjoy.png
- [ ] movie-gifs/trumen.[jpg|gif|mp4|webm]
- [ ] search_preview.png
- [ ] search_preview_no_documents.png
- [ ] search-synonyms.png

@mdubus recently updated some of these if I'm not wrong, so whoever is in charge of this issue might want to check her workflow and replicate it for consistency's sake.

## References
Issue on core: https://github.com/meilisearch/meilisearch/issues/2119
Discussion thread: https://github.com/meilisearch/documentation/discussions/1365#discussioncomment-2059889
