### ISSUE TITLE
v0.26: update mentions of ISO 8601

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1458]
## Summary

There has been a confusion when implementing time formats in Meilisearch: though the specifications said ISO 8601, we have actually implemented RFC 3339 (which seems to be very similar but still has some minor formatting differences.)

We will continue using RFC 3339 everywhere in Meilisearch, so the docs need to replace mentions of ISO 8601 with RFC 3339.  

**Note:** the only exception to this update is the `duration` field included on `task` objects will still follow ISO 8601. This is because RFC 3339 does not define a way to express a process's duration.

## Tasks

- [x] Find mentions of ISO 8601
- [x] Replace mentions of ISO 8601 with RFC 3339
- [x] If automating the above tasks with a find-and-replace tool, double-check the Task API remains unchanged.

## References
Issue on core: https://github.com/meilisearch/meilisearch/issues/2172#issuecomment-1042798896
Spec: https://github.com/meilisearch/specifications/pull/114
