### ISSUE TITLE
v0.27: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1530]
## Research (weeks 1-4 / 2022-03-15 to 2022-04-12)
- [x] Kick-off open-source team sync: 2022-03-15 (private channel)
- [x] Create roadmap issue #1530 
- [x] Create planned changes issue #1531 
- [x] Create spec review issue #1532 
- [x] Assign spec reviews
- [x] Review specs
- [x] Spec book club meeting: 2022-04-11 (private channel) (summary: https://github.com/meilisearch/documentation/issues/1532#issuecomment-1095071402)

## Planning (week 4 / 2022-04-12 to 2022-04-14)
- [x] Create milestone https://github.com/meilisearch/documentation/milestone/6
- [x] Meet with other opensource teams for final briefing: 2022-04-12 (private channel)
- [x] Create issues according to information gathered during research: 2022-04-13
- [x] Collectively assign issues: 2022-04-14 (private channel)
- [x] Create staging PR #1590 

## Implementation (weeks 5-8 / 2022-04-18 to 2022-05-05)
- [x] PRs with code samples created (deadline: 2022-04-21)
- [x] Final list of code samples sent to @meilisearch/integration-team (deadline: 2022-04-26)
- [x] All PRs created and open for review (deadline: 2022-04-28) [usually 1 SME and 1 docs team member]
- [x] All PRs approved (deadline: 2022-05-04)

## Release (week 8 / 2022-05-09)
- [x] Merge staging PR into master
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit as v0.27
- [x] Close milestone

---

_Scheduled release date:_ 09/05/2022

**Comment by guimachiavelli** [comment]
v0.27 released, docs deployed, v0.27 merge commit tagged, all roadmap tasks done.

v0.27 officially finalised.
