### ISSUE TITLE
v0.27: Update Docker paths

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1576]
Due to Docker's peculiarities, the current Docker image and instructions can result in users having to balance three different data locations (one for each of database, snapshot, and dumps).

v0.27 alleviates some of the complexity involved with Docker. The most direct effect to users is that the meilisearch binary has been moved from `./meilisearch` to `meilisearch` _in Docker installs_. There is no effect on the location of binaries for other install method.

## Tasks
- [ ] update Docker install instructions on Quick Start so examples point to `meilisearch`, not `./meilisearch`;
- [ ] check for other Docker code samples;
- [ ] if any code samples are found, update paths on those too

## References
- https://github.com/meilisearch/meilisearch/issues/2235
- SME: @curquiza

**Comment by maryamsulemani97** [comment]
> update Docker install instructions on Quick Start so examples point to `meilisearch`, not `./meilisearch`;

Nor sure I get this. Currently, we have:
 ```
docker run -it --rm \
    -p 7700:7700 \
    -v $(pwd)/data.ms:/data.ms \
    getmeili/meilisearch:latest
```

How do I update this?

**Comment by maryamsulemani97** [comment]
Dk anything about Docker, but don't we currently use `meilisearch` instead of `./meilisearch`?
I found three code samples in the docs:

[1. ](https://docs.meilisearch.com/learn/advanced/updating.html#verify-your-database-version)
```
docker run -it --rm \
    -p 7700:7700 \
    -v "$(pwd)/data.ms:/data.ms" \
    getmeili/meilisearch:v0.X.X
```
[2.](https://docs.meilisearch.com/learn/cookbooks/search_bar_for_docs.html#run-the-scraper)
```
docker run -t --rm \
  --network=host \
  -e MEILISEARCH_HOST_URL='http://localhost:7700' \
  -e MEILISEARCH_API_KEY='myMasterKey' \
  -v <absolute-path-to-your-config-file>:/docs-scraper/config.json \
  getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json
```

[3.](https://docs.meilisearch.com/learn/getting_started/quick_start.html#local-installation)
```
docker pull getmeili/meilisearch:latest

# Launch Meilisearch
docker run -it --rm \
    -p 7700:7700 \
    -v $(pwd)/data.ms:/data.ms \
    getmeili/meilisearch:latest
```
```

**Comment by curquiza** [comment]
Thanks @maryamsulemani97 for the investigation.
The second one is docs-scraper, so, not related to the docker image change for Meilisearch
The first and third one does not use the binary, so no `./meilisearch` to transform into `meilisearch`.
However, the mounted volume command should be changed by `-v $(pwd)/meili_data:/meili_data`.
