### ISSUE TITLE
v0.27: Typo tolerance configuration

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1580]
Though users could play around with the typo ranking rule to have some influence over the weight of typos in a search, they had no actual control over typo tolerance.

v0.27 introduces a new index setting, typo-tolerance, which allows users to selectively disable typo tolerance (e.g. for an attribute), minimum word size for types, disable typo tolerance altogether, etc.

## Tasks
- [x] create a new API reference page
- [x] create new section on learn/configuration/settings.md describing new index settings;
- [x] create a mini-guide on learn/configuration/ (e.g. like learn/configuration/distinct.md);
- [x] rename learn/advanced/typotolerance.md to something like Levenshtein algorithm;
- [x] update table on "Telemetry" page
- [x] update errors page

## References
- https://github.com/meilisearch/meilisearch/issues/2213
- https://github.com/meilisearch/specifications/pull/117
- SME: @MarinPostma
