### ISSUE TITLE
v0.27: New instance options `--max-indexing-memory` and `--max-indexing-threads`

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1581]
These two new instance options give users some influence over resource usage when indexing.

_Important: --max-indexing-memory is not completely reliable and has some margin of error—meaning, an instance with --max-indexing-memory=2gb still go a bit over that limit. We don't have enough data to say how big the error margin is._

## Tasks
- [x] add `--max-indexing-memory` and `--max-indexing-threads` to configuration overview (under `/learn/configuration`
- [x] mention these two new options on "Indexation and performance"
- [ ] also mention options on the FAQ

## References
- https://github.com/meilisearch/meilisearch/issues/2212
- https://github.com/meilisearch/specifications/pull/119
- SME: @curquiza
