### ISSUE TITLE
v0.27: Add support for nested document fields

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1582]
v0.27 allows indexation and searching of nested fields:

```json
{
  "id": 1,
  "title": "Red Wolf, Black Leopard",
  "author": {
    "firstName": "Marlon",
    "surname": "James",
  }
}
```

It's good to keep in mind that one of the main reasons this feature has been added is because many users assume it already exists. This indicates that our changes regarding this new feature should be relatively minor.

## Tasks
- [x] update learn/advanced/datatypes.md with info on nested fields;
- [x] update Index settings API reference of settings that accept attributes with a note/tip/etc block informing nested fields are supported;
- [x] update a few code samples so they include nested fields? Without any explanation, just so users see the behaviour naturally integrated across different use-cases

## References
- https://github.com/meilisearch/meilisearch/issues/2211
- https://github.com/meilisearch/specifications/pull/121
- SME: @irevoire
