### ISSUE TITLE
v0.28: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1681]
## Planning (week 1-5 / 2022-05-07 to 2022-06-14)
- [x] Kick-off open-source team sync: 2022-03-17 (private channel)
- [x] Create milestone https://github.com/meilisearch/documentation/milestone/7
- [x] Create roadmap issue #1681
- [x] Create planned changes issues
- [x] Meet with other opensource teams for final briefing: 2022-06-14 (private channel) (private link to [meeting notes](https://www.notion.so/meilisearch/3988b345b5b248948a4a0dc5932a18ce?v=2c4c006e484a48b7a5b73599fec157b6&p=7b7e83b69f9145fbb44942475e50607d))
- [x] Collectively pre-assign issues: 2022-06-09 (private channel)
- [x] Create staging PR #1707 

## Implementation (weeks 5-8 / 2022-06-14 to 2022-07-05)
- [x] PRs with code samples created (deadline: 2022-06-23)
- [x] Final list of code samples sent to @meilisearch/integration-team (deadline: 2022-07-04)
- [x] All PRs created and open for review (deadline: 2022-06-27) [reviewers should usually be 1 SME and 1 docs team member]
- [x] All PRs approved (deadline: 2022-07-06)
- [x] Edit release blog post — @meilisearch/devrel-team will deliver the first draft by 2022-07-05)
- [x] Review changelog https://github.com/meilisearch/core-team/pull/13

## Release (week 8 / 2022-07-11)
- [x] Merge staging PR into master
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit as v0.28
- [x] Close milestone

---

_Scheduled release date:_ 2022-07-11

**Comment by guimachiavelli** [comment]
## PR status (2022-06-30)

### Waiting for docs team review
- #1738
- #1759
- #1763
- #1761

### Waiting for SME review
- #1728 (ping SME on 2022-07-05)
- #1730 (ping SME on 2022-07-05)
- #1753 (ping SME on 2022-07-04)

### Ready to merge
- #1732
- #1734
- #1736

### Merged
- #1756
- #1752
- #1746 
- #1744
- #1735
- #1733

**Comment by guimachiavelli** [comment]
## PR status (2022-07-04)

### WIP
- #1753 
- #1738 (approved, but @maryamsulemani97 will add more on deterministic keys)

### Waiting for docs team review

### Waiting for SME review
- #1728 (ping SME on 2022-07-05)
- #1730 (ping SME on 2022-07-05)
- #1761
- #1759

### Ready to merge
- #1763
- #1767
- #1766
 
### Merged
- #1756
- #1752
- #1746 
- #1744
- #1735
- #1733 
- #1732
- #1734
- #1736

**Comment by guimachiavelli** [comment]
# PR status (2022-07-11)

All PRs approved and merged. Release ready for deployment.
