### ISSUE TITLE
v0.29: Updates to the `filter` search parameter

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1853]
v0.29 will expand functionality of `filter`:

- New `IN` operator;
- New `EXIST` operator;
- Updated `NOT` operator behavior;
- Filter values identical to filter operators must be enclosed in quotation marks (`x = 1 AND y = 0` vs `x = "AND"`).

## Tasks
- [ ] update `/reference/api/search.md`
- [ ] update `/learn/advanced/filtering_and_faceted_search.md`
- [ ] update `learn/getting_started/filtering_and_sorting.md`
- [ ] search for other articles mentioning and update them if necessary

## References
Issue: https://github.com/meilisearch/meilisearch/issues/2580
SMEs: @loiclec, @curquiza
