### ISSUE TITLE
Roadmap v0.29

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1856]
## Planning (2022-07-11 to 2022-08-29)
- [x] Kick-off open-source team sync: 2022-08-12 (private channel)
- [x] Create milestone https://github.com/meilisearch/documentation/milestone/8
- [x] Meet with other opensource teams for final briefing: 2022-06-14 (private channel)
- [x] Collectively pre-assign issues: 2022-09-01 (private channel)
- [x] Create planned changes issues 2022-09-01
- [x] Create roadmap issue
- [ ] Create staging PR

## Implementation (2022-08-29 to 2022-10-03)
- [ ] Send final list of code samples sent to @meilisearch/integration-team (2022-09-26)
- [ ] All PRs created and open for review (2022-09-15) [reviewers should usually be 1 SME and 1 docs team member]
- [ ] All PRs approved (2022-09-29)
- [ ] Agree scheduling details of release blog post with @meilisearch/devrel-team
- [ ] Edit release blog post
- [ ] Final changelog review https://github.com/meilisearch/core-team/pull/17

## Release (2022-10-03)
- [ ] Merge staging PR into master
- [ ] Notify #ms-releases (private slack channel) once documentation is live
- [ ] Tag the merge commit as v0.29
- [ ] Close milestone

---

_Scheduled release date:_ 2022-10-03
