### ISSUE TITLE
v0.30: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1932]
## Planning (2022-10-04 to 2022-10-31)
- [x] Kick-off open-source team sync: 2022-10-04 (private channel)
- [x] Create roadmap issue
- [x] Create milestone https://github.com/meilisearch/documentation/milestone/9
- [x] Collectively pre-assign issues: 2022-10-24 (private channel)
- [x] Create planned changes issues: 2022-10-26
- [x] Create staging: PR 2022-10-26
- [x] Meet with other opensource teams for final briefing: 2022-11-02 (private channel)

## Implementation (2022-11-01 to 2022-11-24)
- [x] All PRs created and open for review (2022-11-14) [reviewers should usually be 1 SME and 1 docs team member]
- [x] Send final list of code samples sent to @meilisearch/integration-team (2022-11-17)
- [x] All PRs approved (2022-11-22)
- [x] Agree scheduling details of release blog post with @meilisearch/devrel-team
- [x] Edit release blog post
- [x] Final changelog review

## Release (2022-11-28)
- [x] Merge staging PR into main
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit as v0.30
- [x] Close milestone

---

_Scheduled release date:_ 2022-11-28
