### ISSUE TITLE
v0.30: New environment variables

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1965]
On <=v0.29, a few instance options were only available via the CLI. v0.30 adds new environment variables, making all instance options available to all configuration methods.

List of existing CLI option with their new env var equivalents:

`--import-dump -> MEILI_IMPORT_DUMP`
`--ignore-missing-dump -> MEILI_IGNORE_MISSING_DUMP`
`--ignore-dump-if-db-exists -> MEILI_IGNORE_DUMP_IF_DB_EXISTS`
`--import-snapshot -> MEILI_IMPORT_SNAPSHOT`
`--ignore-missing-snapshot -> MEILI_IGNORE_MISSING_SNAPSHOT`
`--ignore-snapshot-if-db-exists -> MEILI_IGNORE_SNAPSHOT_IF_DB_EXISTS`

## Tasks
- [x] `/learn/configuration/instance_options.md`: update flag boxes
- [x] `/learn/configuration/instance_options.md`: add new env vars
  - [x] `--import-dump -> MEILI_IMPORT_DUMP`
  - [x] `--ignore-missing-dump -> MEILI_IGNORE_MISSING_DUMP`
  - [x] `--ignore-dump-if-db-exists -> MEILI_IGNORE_DUMP_IF_DB_EXISTS`
  - [x] `--import-snapshot -> MEILI_IMPORT_SNAPSHOT`
  - [x] `--ignore-missing-snapshot -> MEILI_IGNORE_MISSING_SNAPSHOT`
  - [x] `--ignore-snapshot-if-db-exists -> MEILI_IGNORE_SNAPSHOT_IF_DB_EXISTS`
- [x] update `/learn/advanced/snapshops.md`
- [x] update `/learn/advanced/dumps.md`

## References
- issue on core: https://github.com/meilisearch/meilisearch/issues/2721
- spec: https://github.com/meilisearch/specifications/pull/190
- SME: @irevoire
