### ISSUE TITLE
v0.30: Numbered pagination

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1966]
v0.30 allows users to get the exhaustive number of search results and create traditional numbered pagination updates.

## Summary
- Default behaviour remains the same: pagination with `limit` and `offset`
- Using any of the two new search parameters (`page` and `hitsPerPage`) triggers and exhaustive search
- Exhaustive search query responses include: `hitsPerPage`, `page,` and `totalPages`
- Exhaustive search query responses do not include: `estimatedTotalHits`

## Tasks
- [x] Update `/reference/api/search.md` 
  - [x] add section explaining `estimatedTotalHits` and `totalHits`
  - [x] add new parameter: `hitsPerPage`
    - [x] summary
    - [x] description
    - [x] code sample
  - [x] add new parameter: `page`
    - [x] summary
    - [x] description
    - [x] code sample
  - [x] add new POST response fields: 
    - [x] `totalHits`
    - [x] `totalPages`
    - [x] `hitsPerPage`
    - [x] `page`
  - [x] add new GET response fields: 
    - [x] `totalHits`
    - [x] `totalPages`
    - [x] `hitsPerPage`
    - [x] `page`
- [x] Update pagination guide

## References
- Issue on core: https://github.com/meilisearch/meilisearch/issues/2577
- Prototype discussion: https://github.com/meilisearch/meilisearch/discussions/2635
- PR on core: https://github.com/meilisearch/meilisearch/pull/2601
- SMEs: @ManyTheFish, @gmourier

**Comment by ManyTheFish** [comment]
I add some corner cases, feel free to document them or not accordingly to your information strategy.

- the first page is page 1, however, asking for page 0 will compute a search query and return the exhaustive value of `totalPages` and `totalHits` without returning any document
- making a query with an `hitsPerPage` set to 0 will return the exhaustive value of `totalHits` but the value of `totalPages` will be 0 and no document will be returned.
