### ISSUE TITLE
Add versioning on documentation

### ISSUE THREAD

**Issue by qdequele** [meilisearch/documentation#197]
At this time, an external user arriving on the [documentation](https://docs.meilisearch.com/) don't know which version of Meilisearch the documentation is for.  It could be great to add like on other documentation, the ability to get the version on the navigation bar and to switch easily between them. 

## Examples

- [ReactJS](https://reactjs.org/docs/getting-started.html)
- [VueJS](https://vuejs.org/v2/guide/)

We prefer the way React handles it.

## Proposal

We can use the [versioning](https://titanium-docs-devkit.netlify.com/guide/versioning.html) plugin for Vuepress

By default, the documentation should render the last version. But It's could be cool if we can also have a "master"/"beta" version for the latest documentation commit. 

## Sub issues
- [ ] #193 Add version of MeiliSearch in the header-bar.
- [ ] #155 Release a documentation for the v0.8.5 tag
- [ ] #96 Create a reminder that the documentation follows the master branch and not the tag

**Comment by maryamsulemani97** [comment]
Closing this as we will not use the Vuepress plugin for versioning. The new site will have it, but not in the first version
