### ISSUE TITLE
v1.0: prepare migration + versioning documentation

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#2057]
# Meilisearch v1.0

Pre-release begins: 9 January
Release date: 6 February

## Prepare migration + versioning documentation

With the release of version 1, one of our highest priorities is making sure that users of older versions can migrate to version 1 without problems.

I don't believe it's necessary to release a migration guide specifically for v1.0. If we did, I do not think the content would differ significantly from our general updating guide.

However, we _must_ **organize, update, and reframe our existing version upgrade documentation**.

This is a tracking issue to help us execute a comprehensive versioning + migration strategy.

### To do

The following is a checklist of tasks needed to prepare our migration docs for v1. Each item should be connected to an issue; if not, a link will be added once the issue has been created.

**EDIT:** we decided not to create a separate updating guide for `systemctl` users. Instead, we revised and streamlined our existing updating guide. 

- ~~[ ] Create + release cloud updating guide~~
- [x] [Improve updating guide for `systemctl` users](https://github.com/meilisearch/documentation/pull/2058)
- [x] [Create update troubleshooting guide](https://github.com/meilisearch/documentation/issues/2097)
- [x] [Create + release versioning policy](https://github.com/meilisearch/documentation/issues/2113)
  - [x] Core versioning policy
  - [x] Integrations versioning policy
  - [x] [Documentation versioning policy + how to access previous versions of the documentation](https://github.com/meilisearch/documentation/issues/2070)
- [x] [Create a new sidebar section devoted to updating + versioning](https://github.com/meilisearch/documentation/issues/2096)
- ~~[ ] [Improve contributing files](https://github.com/meilisearch/documentation/issues/1881)~~
