### ISSUE TITLE
v1.0: Roadmap

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2064]
## Planning (2022-11-29 to 2023-01-09)
- [x] Kick-off open-source team sync:  (private channel)
- [x] Create roadmap issue
- [x] Create milestone
- [x] Collectively pre-assign issues
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Updating the config file link in `learn/cookbooks/running_production.md`
- [x] Create staging: https://github.com/meilisearch/documentation/pull/2098
- [x] Meet with other opensource teams for final briefing: (private channel)

## Implementation (2023-01-09 to 2023-02-02)
- [x] All PRs created and open for review (2023-01-23) [reviewers should usually be 1 SME and 1 docs team member]
- [x] Send final list of code samples sent to @meilisearch/integration-team (2022-01-30)
- [x] All PRs approved (2023-01-31)
- [x] Agree scheduling details of release blog post with @meilisearch/devrel-team
- [x] Edit release blog post
- [x] Final changelog review

## Release (2023-02-06)
- [x] Merge staging PR into main
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit as v1.0
- [x] Close milestone

---

_Scheduled release date:_ 2023-02-06
