### ISSUE TITLE
v1.1: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2182]
## Planning: 2023-02-07 to 2023-03-07
- [x] Kick-off open-source team sync meeting (private channel): _2023-02-07_
- [x] Create milestone
- [x] Create roadmap issue
- [x] Pre-release changelog review: _2023-03-06_
- [x] Final open-source teams briefing (private channel): _2023-03-07_
- [x] Collectively assign issues: _2023-03-08_
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Code sample tracker
- [x] Create staging PR 

## Implementation: 2023-03-07 to 2023-03-30
- [x] All PRs created and reviews requested: _2023-03-22_
- [x] Release blog post ready for editorial review @meilisearch/devrel-team: _2023-03-27_
- [x] Send final list of code samples sent to @meilisearch/integration-team: _2023-03-28_
- [x] All PRs approved: _2023-03-30_
- [x] Release blog post edited: _2023-03-30_
- [x] Final changelog review: _2023-03-30_

## Deploy: 2023-04-03
- [x] Merge staging PR into main
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit as v1.1
- [x] Close milestone

---

**Scheduled release date:** _2023-04-03_
