### ISSUE TITLE
v1.1: Configure CSV delimiter

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2204]
v1.1 adds a new `csvDelimiter` query parameter to `POST`/`PUT` routes on the `/documents` endpoint.

`csvDelimiter` is optional and accepts a one-character string which replaces the comma (`,`) as the field separator in CSV documents.

## Tasks
- [x] Update `/reference/api/documents.md` (POST and PUT)
- [x] Update `/learn/core_concepts/documents.md` (lines 107-127)
- [x] Add new error code `invalid_document_csv_delimiter` to `/reference/errors/error_codes.md`

## References
- issue on core: https://github.com/meilisearch/meilisearch/issues/3442 and https://github.com/meilisearch/meilisearch/issues/3533
- spec: https://github.com/meilisearch/specifications/pull/221
- SME: @irevoire

**Comment by guimachiavelli** [comment]
@irevoire, what is the expected behaviour of setting `csvDelimiter` and sending data in a format other than CSV? Will Meilisearch simply ignore it?
