### ISSUE TITLE
v1.1: Experimental `/metrics` endpoint

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2206]
This is an experimental feature adding a new `/metrics` endpoint. Since the feature is tagged with experimental, the endpoint is not available by default and compatibility between Meilisearch versions is not assured.

The docs team will not fully document this feature. Instead, we will add a brief explanation and a link to the GitHub discussion. We will also try to support the engine team by reviewing the existing text.

## Tasks
- [x] Create new "Experimental features" section
- [x] Create metrics.md under new section
- [ ] Review https://github.com/meilisearch/product/discussions/625

## References
- issue on core: https://github.com/meilisearch/meilisearch/issues/3523
- spec: https://github.com/meilisearch/specifications/pull/174
- SME: @irevoire
