### ISSUE TITLE
Migration: Implement MDX linting

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2239]
Implement MDX linting. This should most likely use [`eslint`](https://eslint.org/) and [`eslint-mdx`](https://github.com/mdx-js/eslint-mdx).

## Tasks

- [ ] Install and setup `eslint`
- [ ] Install and setup `eslint-mdx`
- [ ] Create CLI script to run linter
- [ ] Install and setup `eslint`/`eslint-mdx` plugins on VSCode
- [ ] Document how to run `eslint` on both CLI and VSCode
- [ ] Create GitHub action to run linter on push

**Comment by guimachiavelli** [comment]
I have renamed the issue, rewritten the issue description, and added a list of tasks.

**Comment by maryamsulemani97** [comment]
eslint is a JavaScript linter and may not be useful to use. [Here's a list of rules created using eslint](https://eslint.org/docs/latest/rules/)

**Comment by guimachiavelli** [comment]
This issue is now the responsibility of an external team and will be monitored in their preferred platform.
