### ISSUE TITLE
Migrate recent changes 

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2245]
Migrate recent changes like v1.1. We may need to do this manually instead of rebasing

The following list contains PRs opened after #2226

## Migrate changes from before v1.1
- [x] Migrate changes from #2230 
  - Done in #2266 
- [x] Migrate changes from #2233 
  - Done in #2267 
- [x] Migrate changes from #2254 
  - Done in #2268 
- [x] Migrate changes from #2250 
  - Done in #2269 
## Migrate v1.1 changes
- [x] Migrate changes from #2193 
  - Done in #2272

**Comment by maryamsulemani97** [comment]
fixed with #2266. #2267, #2268, #2269, and #2272
