### ISSUE TITLE
Improve readability

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#2377]
One of our planned projects for Q2 2023 is a **readability review of our documentation**.

~Using aggregated readability metrics, we will calculate a score for each of our pages. We will then identify "low-hanging fruit" to increase the scores across the board (e.g. lowering the site's sentence-length limit) and take action.~

~For pages with unusually high readability scores, we may take special action, especially if the page is involved in new user onboarding.~

_Edit by Maryam (June 12, 2023)_

## Phase one: visual effectiveness

- [ ] Reduce prose chunks
  - This can be done by:
    - Adding new headers to the prose
    - Converting the text to bullets or tables 
    - Add more code samples or replace existing text with code samples
- [x] Reduce the use of containers (tips, warnings, danger boxes) 
   - Related issue: https://github.com/meilisearch/documentation/issues/2474
   - Related PR: https://github.com/meilisearch/documentation/pull/2466
- [ ] Separate understanding-oriented sections from task-oriented sections
   - Users should be able to get a task done without understanding how the engine works

See [Notion page](https://www.notion.so/meilisearch/Readability-pages-acc3dd3918574bbd90c03374691c6c53)

**Comment by guimachiavelli** [comment]
Due to the reorg and change of priorities, we do not have enough resources to allocate to assess readability metric.
