### ISSUE TITLE
Meilisearch 101 v2

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#2379]
# Meilisearch 101 v2: beginner tutorial

We will use the Meilisearch 101 as the basis for a beginner tutorial (think ”My first Meilisearch project”). Will cover at minimum:

- Launching with master key
- Adding documents
- Setting searchable + displayed attributes
- Making searches with filters, sorts, and geosearch

Could also include:

- Re-ordering ranking rules
- Creating a basic search interface w/ instantsearch
- Facets

This is a beginner tutorial, but it’s nonetheless important to define our vision for tutorials beyond this one. How could it be extended into an “intermediate” and/or “advanced” tutorial?

**Comment by guimachiavelli** [comment]
After discussing the 101 v2 over a call, we have tightened this issue's focus. The 101 v2 should:
- Be an explicit continuation of the "quick start"
- Be short and to the point
- Target users who learn by coding instead of reading
- Focus on quickly getting a front end up and running

It should contain the following content and nothing else:
- Basic index settings: search and displayed attributes
- Basic relevancy customisation: moving ranking rules around
- Creating a basic front-end

Given its tight focus, the 101 v2 will not mention filtering, sorting, geosearch, nor facets as suggested in the first comment.

## Tasks
- [ ] Create new tutorial under the "Getting started" section
- [ ] Consider removing "Front-end integration" from the site, possibly folding the little content it has into the new tutorial
- [ ] Remove the section "Meilisearch 101"
  - [ ] Remove "Filtering and sorting", "Customizing relevancy", and "Getting ready for production"
  - [ ] Add redirects pointing these pages to the new tutorial

**Comment by guimachiavelli** [comment]
Due to Meilisearch's shift to focussing on the cloud offering, the Meilisearch 101 needs to be completely rethought—and is currently much less important.

We have removed the 101 to prevent content duplication and the confusion that might spring from that (e.g. someone searching for filters ends up in the filtering and sorting 101 instead of the filtering guide).
