### ISSUE TITLE
v1.2: Roadmap

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2404]
## Planning: 2023-05-10 - 2023-05-11
- [x] Kick-off open-source team sync meeting (private channel): _2023-04-04_
- [x] Create milestone
- [x] Create roadmap issue
- [x] Pre-release changelog review: _2023-05-08_
- [x] Final open-source teams briefing (private channel): _2023-05-09_
- [x] Collectively assign issues: _2023-05-10_
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Code sample tracker
- [x] Create staging PR 
- [x] Create issue on https://github.com/meilisearch/meilisearch.com updating the docs version number 

## Implementation: 2023-05-10 - 2023-06-01
- [x] All PRs created and reviews requested: 2023-05-16
- [x] Release blog post ready for editorial review @meilisearch/devrel-team: _2023-05-29_
- [x] Send final list of code samples sent to @meilisearch/integration-team: _2023-05-29_
- [x] All PRs approved: 2023-05-30
- [x] Release blog post edited: 2023-06-01
- [x] Final changelog review: 2023-05-30

## Deploy: 2023-06-05
- [x] Merge staging PR into main
- [x] Merge redirect PRs in meilisearch.com
     - ~https://github.com/meilisearch/meilisearch.com/pull/120~ https://github.com/meilisearch/meilisearch.com/pull/127 
- [x] Merge version update PR in meilisearch.com:
     - https://github.com/meilisearch/meilisearch.com/pull/118 
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit as v1.2
- [x] Close milestone

---

**Scheduled release date:** _2023-06-05_
