### ISSUE TITLE
Migrate redirects from old website

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2450]
When we migrated the documentation website from Vuepress to Next.js, we decided not to implement any redirects. We have now realised this was a bad decision that has lead to many complaints by users. Whilst speaking to @bidoubiwa, we also noticed that changes in #2170 might have been a net negative and redirects pointing to important pages.

To fix things, we need to implement all redirects from the previous website to the new website.

## Tasks

- [ ] Create script converting old redirects file to [next.js redirects](https://nextjs.org/docs/pages/api-reference/next-config-js/redirects) (to be done by @bidoubiwa)
- [x] Obtain redirects file pre-#2170
- [x] Obtain the last redirects file before next.js migration
- [x] Update redirects file pre-#2170 with redirects from last redirects file
- [x] Pass this file to @bidoubiwa so she can run the conversion script
- [ ] Update the current next.js file with the converted redirects
- [ ] Once next.js has all redirects, re-run @bidoubiwa's broken link checker to see if we have any remaining broken links

**Comment by maryamsulemani97** [comment]
This is the redirects file before #2170. I added two new sections(lines 206-219):
- Redirects added after migration
- Redirects added after migration that haven’t been merged

[Redirects.md](https://github.com/meilisearch/documentation/files/11662187/Redirects.md)

**Comment by guimachiavelli** [comment]
The following redirects have been deployed yesterday:

```
/learn/what_is_meilisearch/search_preview.html                             /learn/getting_started/search_preview.html
/learn/advanced/pagination.html                                                        /learn/front_end/pagination.html
/learn/getting_started/quick_start.html#front-end-integration       /learn/front_end/front_end_integration.html
```

Probably doesn't matter, though.

**Comment by bidoubiwa** [comment]
They help! Thanks a lot :)

**Comment by curquiza** [comment]
@guimachiavelli what is the state of this issue, aren't done with all redirections?

**Comment by curquiza** [comment]
Discussed with @guimachiavelli 
We did not get more complain about redirection for a while, so we close the issue.
The main work that has not been done is:

> Create script converting old redirects file to [next.js redirects](https://nextjs.org/docs/pages/api-reference/next-config-js/redirects)

If we get any issue in the future, we should reconsider this task 👆
