### ISSUE TITLE
v1.3: Roadmap

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2467]
## Planning: 
- [x] Kick-off open-source team sync meeting (private channel): _2023-06-06_
- [x] Create milestone
- [x] Create roadmap issue
- [x] Pre-release changelog review:
- [x] Final open-source teams briefing (private channel): _2023-07-04_
- [x] Collectively assign issues: 
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Code sample tracker
- [x] Create staging PR 
- [x] Create issue on https://github.com/meilisearch/meilisearch.com updating the docs version number:
   - [x] https://github.com/meilisearch/meilisearch.com/pull/132  

## Implementation: 202307-03 - 2023-07-31
- [x] All PRs created and reviews requested: 
- [x] Release blog post ready for editorial review @meilisearch/devrel-team: _2023-07-24_
- [x] Send final list of code samples sent to @meilisearch/integration-team: _2023-07-24_
- [x] All PRs approved
- [x] Final changelog review

## Deploy: 2023-07-31
- [x] Merge staging PR into main
- [x] Merge redirect PRs in meilisearch.com (if any)
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit as v1.3
- [x] Close milestone

---

**Scheduled release date:** _2023-07-31_

**Comment by maryamsulemani97** [comment]
Since most of the docs team will be off during the first two weeks of the implementation phase, we will start work on draft PRs early and have them ready by 2023-06-22
