### ISSUE TITLE
v1.3: Define search field at search time

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2478]
v1.3 introduces a new search parameter, `attributesToSearchOn`.

`attributesToSearchOn` is a search parameter accepting an array of strings indicating one or more document attributes. Queries using `attributesToSearchOn` will restrict the search to the indicated attributes.

Given the following dataset:

```json
{
  "id": 0,
  "name": "Our Wives Under the Sea",
  "genre": ["horror", "scifi"],
  "synopsis": "A woman returns to her wife transformed after a deep-sea adventure."
},
{
  "id": 1,
  "name": "A Strange and Stubborn Endurance",
  "genre": ["adventure"],
  "synopsis": "A man must overcome trauma and fight off a mysterious assassin."
}
```

And the following query:

```json
{
  "q": "adventure",
  "attributesToSearchOn": ["genre"]
}
```

Meilisearch will only return document `1`.

Both documents contain the word adventure, but `"attributesToSearchOn": ["genre"]` instructs Meilisearch to only consider results found on the `genre` field.

## Tasks
- [x] Add `attributesToSearchOn` to `/reference/api/search#search_parameters`
- [x] Update search parameter tables in `/reference/api/search` and `/reference/api/multi_search`
- [ ] (Optional) Add `<Capsule />` mentioning `attributesToSearchOn` to `/learn/fine_tuning_results/filtering`

## References
- engine issue: https://github.com/meilisearch/meilisearch/issues/3772
- engine PR: https://github.com/meilisearch/meilisearch/pull/3834
- PRD (private): https://www.notion.so/meilisearch/Define-Fields-To-Search-On-At-Search-Time-0725a20ed5bd46b593683a67697d3e7b
- SME: @ManyTheFish

**Comment by ManyTheFish** [comment]
Hello @guimachiavelli,
Some details about the feature:
- giving the attributes in a different order than the order set in the settings `searchableAttributes` doesn't reorder the fields' rank for the `attributes` ranking rule
- if the user doesn't set an  array of strings,  an error is thrown under the code `invalid_attributes_to_search_on`:
```json
{
    "message": "Invalid value type at `.attributesToSearchOn`: expected an array, but found a string: `\"hello\"`",
    "code": "invalid_attributes_to_search_on",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#invalid_attributes_to_search_on"
}
```
- if the user sets an attribute that isn't in the settings `searchableAttributes` list, an error is thrown under the code `invalid_attributes_to_search_on`:
```json
{
    "message": "Attribute `unknown` is not searchable. Available searchable attributes are: `id, title`.",
    "code": "invalid_attributes_to_search_on",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#invalid_attributes_to_search_on"
}
```
- a variant exists for the previous error message if some of the `searchableAttributes` are not in the `displayAttributes`, all the attributes listed in both lists will be listed in the error message but the ones that are not in the `displayAttributes` will be hidden and the `<..hidden-attributes>` mark will be added to the listed attributes in the error message:
```json
{
    "message": "Attribute `unknown` is not searchable. Available searchable attributes are: `id, title, <..hidden-attributes>`.",
    "code": "invalid_attributes_to_search_on",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#invalid_attributes_to_search_on"
}
```

See you!

**Comment by guimachiavelli** [comment]
Thanks for the clarification, @ManyTheFish!

A couple of questions: 
1. does `attributesToSearchOn` accept any values besides an array of strings? For example, can I use `"*"` to select all `searchableAttributes`?
2. What is the default value of `attributesToSearchOn`? `null`, `"*"`, `["*"]`, something else entirely?

**Comment by ManyTheFish** [comment]
Hello @guimachiavelli,

> Does attributesToSearchOn accept wildcards? For example, can I use "*" or ["*"] to select all searchableAttributes?

No, the behavior to select all attributes is to not define the field or set it to `null`

> What is the default value of attributesToSearchOn? null, "*", ["*"], something else entirely?

the default value is `null`

**Comment by ManyTheFish** [comment]
Hello @guimachiavelli, there is a small change in the error code `invalid_attributes_to_search_on` becomes `invalid_search_attributes_to_search_on`.

Meanwhile, I've updated the related specifications, I put below the dedicated PR:
https://github.com/meilisearch/specifications/pull/251

Sorry for the late change! See you!

**Comment by guimachiavelli** [comment]
No problem, thanks for letting me know (and for updating the draft PR 🙏)
