### ISSUE TITLE
Create Vercel guide

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2513]
It is important for @meilisearch/devrel-team's current strategy to publish a guide on using Vercel with Meilisearch. Though the (pre-reorg) @meilisearch/docs-team has previously internally the documentation should keep resources focussed on third-party tools to a minimum, the blog does not currently offer enough visibility for the dev rel to meet its goals.

As a temporary solution, we will publish this guide on the documentation, under the Cookbooks section. @guimachiavelli will quickly review the text to ensure it matches the docs website tone and style guides, but @CaroFG will remain this resource's owner.

## Tasks
- [x] Add guide inside `/learn/cookbooks` dir
- [x] Add guide to `/config/sidebar-learn.json` under `Cookbooks`
- [x] Update `.github/CODEOWNERS` assigning @CaroFG as the owner of the document
- [x] Create PR
- [x] Request reviews from @guimachiavelli and one expert (can probably skip the expert if the guide has already been approved by an engineer elsewhere)
