### ISSUE TITLE
Meilisearch Cloud quick start

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2514]
As part of the company's prioritisation of Cloud-related tasks for the foreseeable future, the documentation needs to improve Meilisearch Cloud visibility.

The first step is creating a tutorial walking users through describing Meilisearch Cloud usage. Essentially, a piece analogous to the Quick start, with very low barrier of entry and accessible to completely inexperienced users, but with a focus on the cloud offering.

This tutorial is to be the first in a new section of Meilisearch Cloud-centric pieces.

## Tasks
- [ ] Create Getting started with Meilisearch Cloud tutorial
- [ ] Add new guide to `/learn/getting_started`
- [ ] Update `/learn/getting_started/quick_start.mdx` with link to new tutorial
