### ISSUE TITLE
Highlight Meilisearch Cloud on installation guide

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2515]
As part of the company's prioritisation of Cloud-related tasks for the foreseeable future, the documentation needs to improve Meilisearch Cloud visibility.

Even with the recently added section, it is easy to miss Meilisearch Cloud in this page. We may be able to restructure it so Cloud is more visible.

## Tasks
- [x] Move OS section to a new page
- [x] Remove "Installation" heading
- [x] Reorganise remaining content in three sections: Local, Meilisearch Cloud, Other Cloud providers
- [ ] Move Installing older versions inside a `<Capsule>` at the end of the page
