### ISSUE TITLE
Meilisync guides

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2542]
Meilisearch Cloud has recently deployed a new feature to simplify keeping Meilisearch synchronized with a user's primary database. We need to write a few guides to support this feature and also cover a common user need. Content outlines and instructions have already been primarily developed by @alallema.

Writing responsibility will be shared between @meilisearch/docs-team  and @meilisearch/devrel-team, with docs supplying the first guide and devrel creating the remainder using that as a template.

## Tasks
- [x] Syncing with MySQL and Meilisync
- [x] Syncing with Postgres and Meilisync
- [ ] Syncing with MongoDB and Meilisync
- [ ] Create new "Syncing with a primary database" section under "Learn"

## References
- SME: @alallema 
- [Outline and instructions (private link)](https://www.notion.so/meilisearch/Primary-DBs-with-Meilisearch-cf98503b6e6a40308f4e273ee828820e)
- [Devrel kickoff document (private link)](https://www.notion.so/meilisearch/Syncing-Meilisearch-with-SQL-databases-23414f58997843bf97b3b5a5bbe86444)
