### ISSUE TITLE
v1.4: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2552]
## Planning: 
- [x] Kick-off open-source team sync meeting (private channel): _2023-08-01_
- [x] Create milestone
- [x] Create roadmap issue
- [x] Pre-release changelog review
- [x] Final open-source teams briefing (private channel): _2023-09-05_
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Code sample tracker
- [x] Create staging PR

## Implementation: 2023-09-05 — 2023-09-25
- [x] All PRs created and reviews requested: 
- [x] Send final list of code samples sent to @meilisearch/integration-team: _2023-09-14_
- [x] All PRs approved
- [x] Final changelog review

## Deploy: 2023-09-25
- [x] Merge staging PR into main
- [x] Merge redirect PRs in meilisearch.com (if any)
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit as v1.4
- [x] Close milestone

---

**Scheduled release date:** _2023-09-25_
