### ISSUE TITLE
v1.5: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2590]
## Planning: 
- [x] Kick-off open-source team sync meeting (private channel): _2023-09-26_
- [x] Create milestone
- [x] Create roadmap issue
- [x] Pre-release changelog review
- [x] Final open-source teams briefing (private channel): _2023-10-24_
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Code sample tracker
- [x] Create staging PR

## Implementation: 2023-10-24 — 2023-11-16
- [x] All PRs created and reviews requested: 
- [x] Send final list of code samples sent to @meilisearch/integration-team: _2023-11-09_
- [x] All PRs approved
- [x] Final changelog review

## Deploy: 2023-11-20
- [x] Merge staging PR into main
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit as v1.5
- [x] Close milestone

---

**Scheduled release date:** _2023-11-20_

**Comment by curquiza** [comment]
@brunoocasali I will be OOO when @guimachiavelli sends the code samples, so you will be alone to take care of it for PHP and JS, sorry 😬
