### ISSUE TITLE
v1.5: Experimental feature: Puffin profiler

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2592]
v1.5 adds a new experimental feature allowing for users to export a Puffin report. Puffin is a rust-based profiler that helps programmers visualize the performance impact of internal Meilisearch operations. This is mostly useful to the engine team, but might also assist the support team. 

Activation happens exclusively via the `/experimental-features` API route. Activating this feature will negatively impact performance.

## Tasks
- [x] Create new page: `/learn/experimental/puffin-reports.mdx`
- [x] Update API reference `/reference/api/experimental.mdx`
- [x] Update overview table `/learn/experimental/overview.mdx#current-experimental-features`

## References
- PRD (private link): https://www.notion.so/meilisearch/Export-Puffin-Reports-091df151e71c4edfb7d72f4bf995b3ea
- GitHub discussion: https://github.com/orgs/meilisearch/discussions/693
- issue on engine repo: https://github.com/meilisearch/meilisearch/issues/4121
- SME: @Kerollmops
