### ISSUE TITLE
v1.5: Activate `/metrics` via `/experimental-features` route

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2593]
`/metrics` is an experimental feature allowing users to obtain more data on their instance. It can be activated with a command-line flag.

With v1.5, users will also be able to activate it with the `/experimental-features` API route:

```sh
curl \
  -X PATCH 'http://localhost:7700/experimental-features/' \
  -H 'Content-Type: application/json'  \
  --data-binary '{
    "metrics": true
  }'
```

## Tasks
- [ ] ~~Update `/learn/experimental/metrics.mdx`~~
- [x] Update table in `/learn/experimental/overview.mdx`
- [x] Update API reference (object, responses)

## References
- SME: @curquiza 
- issue on engine repo: https://github.com/meilisearch/meilisearch/issues/4086

**Comment by curquiza** [comment]
@guimachiavelli if I'm correct you don't have to change anything on https://www.meilisearch.com/docs/learn/experimental/metrics since the behavior is not described
