### ISSUE TITLE
v1.5: New `/snapshots` route

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2594]
v1.5 introduces a new API route, `/snapshots`. This route works similarly to `/dumps` and generates snapshots on demand:

```sh
curl \
  -X POST 'http://localhost:7700/snapshots'
```

## Tasks
- [x] Create new page `/reference/api/snapshots.mdx`
- [x] Update `/learn/advanced/snapshots.mdx` with mentions/examples of the new route
- [x] Update telemetry table `/learn/what_is_meilisearch/telemetry.mdx`
- [x] Update `/reference/api/keys.mdx` with new action

## References
- PRD (private link): https://www.notion.so/meilisearch/On-demand-snapshots-5676e542b905459d96eec228da133b00#847ff0cafeb64fe09e8ee7150852b474
- spec: https://github.com/meilisearch/specifications/pull/258
- issue on engine repo: https://github.com/meilisearch/meilisearch/issues/4052
- SME: @irevoire

**Comment by guimachiavelli** [comment]
@irevoire: dump creation tasks have precedence over other tasks and get bumped to the top of the queue. Does the same happen with snapshot creation tasks?

**Comment by curquiza** [comment]
Hello @guimachiavelli 
I asked your question directly to the dedicated page about [usage in the PRD](https://www.notion.so/meilisearch/Usage-On-demand-snapshots-f105c94abb444b61a9d0f94550a5199e) to avoid losing information about usage 😊

**Comment by irevoire** [comment]
Hey @guimachiavelli, yes, the task priorities are specified here: https://specs.meilisearch.com/specifications/text/0060-tasks-api.html#_2-technical-details

1. `taskCancelation`
2. `taskDeletion`
3. `snapshotCreation`
4. `dumpCreation`
5. All other task types with by their enqueued at order.

**Comment by guimachiavelli** [comment]
Apologies, just realised the answer is in the spec: https://github.com/meilisearch/specifications/pull/258/files#diff-e175d37082ef5c813e50d88dbbecba25257def01633496a754c93c3e5fea8c1bR27

> `snapshotCreation` task takes priority over enqueued `tasks`

**Comment by irevoire** [comment]
No problem, https://specs.meilisearch.com/ works pretty well if you don't know where to search in the spec (which is always my case).

<img width="746" alt="image" src="https://github.com/meilisearch/documentation/assets/7032172/62f73601-d155-4491-b438-853986e9be23">
