### ISSUE TITLE
Update Meilisearch Cloud screenshots

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2626]
Meilisearch Cloud recently underwent a few minor UI changes. We need to update articles using the old screenshots so they reflect those changes.

## Tasks
- [x] Contact cloud team: is this a good moment to make new screenshots or do we expect significant UI changes in the coming weeks?
- [ ] Update screenshots on `/learn/getting_started/cloud_quick_start.mdx`
- [x] Create [spreadsheet listing all Meilisearch Cloud screenshots](https://docs.google.com/spreadsheets/d/1okKLa5WoTLW6GT-FdOGqJllFYXJNpDOfMXvFnueKdgQ/edit?usp=sharing), the date it was taken, and the page it illustrates

**Comment by guimachiavelli** [comment]
Cloud team confirms this is a good enough moment. They have committed to create issues on the docs repo whenever there are significant UI changes.
