### ISSUE TITLE
Meilisearch Cloud teams guide

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2635]
A few weeks ago Meilisearch Cloud released teams functionality. Teams allow multiple Cloud users to access and manage the same project. 

There are currently two member statuses in Meilisearch Cloud teams: owner and member. Owners can transfer ownership and access billing information. All users can access, create, and manage indexes and settings.

## Tasks
- [x] Finish gathering information
- [x] Create new guide: `learn/cloud/teams.mdx`
  - [x] Write outline and submit for first technical review
  - [ ] Finish first draft
  - [ ] Finish second draft
