### ISSUE TITLE
Monitoring metrics guide

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2637]
Meilisearch Cloud will soon launch a new feature called monitoring metrics. In short, these are server/performance analytics engineers can use to diagnose issues and measure system status. It include graphs charting search latency, index latency, number of search queries, and bandwidth usage.

The documentation must explain how to activate and deactivate this feature. Additionally, we should study the possibility of a separate overview document for the interface.

## Tasks
- [ ] Create new page in `learn/cloud/monitoring.mdx`
  - [ ] Write outline and submit for first technical review
  - [ ] Finish first draft
  - [ ] Finish second draft

## References
- SME: @gmourier, @Kerollmops
- PRD (private link): https://www.notion.so/meilisearch/Monitoring-Metrics-v1-4782d56795c043799dde33309e73a20f?pvs=4
