### ISSUE TITLE
v1.6: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2651]
## Planning: 
- [x] Kick-off notes (private channel): _2023-11-23_
- [x] Create milestone
- [x] Create roadmap issue
- [x] Pre-release changelog review
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Telemetry updates
    - [x] Code sample tracker
- [x] Create staging PR

## Implementation: 2024-01-02 — 2024-01-11
- [x] All PRs created and reviews requested: _2024-01-08_
- [x] Send final list of code samples sent to @meilisearch/integration-team: _2024-01-08_
- [x] All PRs approved
- [x] Final changelog review

## Deploy: _2024-01-15_
- [x] Merge staging PR into main
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit
- [x] Close milestone

---

**Scheduled release date:** _2024-01-15_
