### ISSUE TITLE
Update AWS with user suggestions

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2663]
This issue compiles feedback received from an AWS user into two actionable tasks.

## Tasks
- [ ] Update `/learn/deployment/aws.mdx`
  - [ ] Mention users may want to add elastic IP to instances to facilitate updating the instance type
  - [ ] Mention users may want to use a more recent version of the general purpose SSD, such as GP2

## Reference
- Original issues: #2366, #2368
- SME: @alallema
