### ISSUE TITLE
Migrating guides from the blog

### ISSUE THREAD

**Issue by Strift** [meilisearch/documentation#2696]
Creating this mega issue to track this project.

## Context & Objectives

This Q1 2024, DevRel and Docs aim to migrate 'how to' content from the [Meilisearch blog](blog.meilisearch.com) to the documentation. 

Goals:
- Improve discoverability of the content (docs has more traffic + better search)
- Improve SEO of the meilisearch.com domain (blog is on a subdomain)

## Scope

We want to prioritize the migration of articles that can have the most impact. The criteria for prioritizing articles include:
- Monthly traffic on the piece
- Matching "Searches without results" analytics
- Strategic alignment with go-to-market activities (ie. frameworks, etc.)
- Up-to-dateness of the content
- Ease of migration

With the ongoing work on improving the docs UX and the upcoming reorganization of its content, we aim to always consider existing limitations to prioritize the migration in the way that is best enabled by the simultaneous activities affecting the documentation as a whole.

## Tasks

> Will link the issues instead as they are created.

Based on [traffic this past year](https://app.usefathom.com/?comparison=none&filters%5B0%5D%5Boperator%5D=is&filters%5B0%5D%5Bproperty%5D=Domain&filters%5B0%5D%5Bvalue%5D=https://blog.meilisearch.com&range=last_365_days&site=QNBPJXIV), the most important pieces to migrate are:

- [ ] Migrate [Laravel full text search guide](https://blog.meilisearch.com/laravel-full-text-search/)
- [ ] Migrate [LangChain semantic search tutorial](https://blog.meilisearch.com/langchain-semantic-search-tutorial/)
- [ ] Migrate [Nuxt ecommerce guide](https://blog.meilisearch.com/nuxt-ecommerce-search-guide/)
- [ ] Migrate [Instant Meilisearch guide](https://blog.meilisearch.com/instant-meilisearch/)
- [ ] Migrate [Strapi v4 plugin guide](https://blog.meilisearch.com/strapi-v4-plugin-meilisearch/)
- [ ] Migrate [Instant Search React guide](https://blog.meilisearch.com/instant-search-react-app/)
- [ ] Migrate [Best practices for fasting indexing](https://blog.meilisearch.com/best-practices-for-faster-indexing/)
- [ ] Migrate [Multi tenancy guide](https://blog.meilisearch.com/multi-tenancy/)
- [ ] Migrate [Strapi guide](https://blog.meilisearch.com/add-meilisearch-to-your-strapi-app/)
- [ ] Migrate [Firebase guide](https://blog.meilisearch.com/firebase-meilisearch/)

For a better idea of other content we are considering migrating, please refer to the [Blog posts migration table](https://www.notion.so/meilisearch/c2eea510874e4033be1356d557407549?v=8e336410d9a34a8fa9644ef50e80bc2f).

**Comment by Strift** [comment]
Hi, after discussing the points above in a meeting with curqui and Thomas, we are now aligned on how to proceed. 🎉 

The goal is to add 10 pieces to the documentation this February. The topics to prioritize are based on the 10 most-visited pieces that are listed in the issue description.

--- 

@guimachiavelli @CaroFG My goal for this week is to finish these pieces:
- #2703 
- #2712 
- #2713

**Comment by Strift** [comment]
Hey,

The deadline of the end of February is approaching. We have 2/10 pieces created. We will likely not meet the deadline.
Most posts cannot be copy-pasted to the docs and require some rewriting (and reviewing), which takes more time than estimated.

---

Last week, I worked on:
- #2714 (merged)
- #2715 (in review)

This week, the priorities are:
1. Merging #2715 
2. Submitting a PR for #2719 
3. Adding the suggested sections and submitting for review #2704

**Comment by curquiza** [comment]
Thank you @Strift 
2 questions
- How bad is it for your work to delay this deadline? (If I'm correct, there is no impact)
- What is the new deadline you suggest?

**Comment by CaroFG** [comment]
I'll be working on migrating Strapi v4 guide this week, issue #2731

**Comment by CaroFG** [comment]
I migrated the LangChain semantic search tutorial #2777

**Comment by guimachiavelli** [comment]
It seems the majority of this transition has been successful. There might still be some lower impact articles we didn't migrate, but since it's been a year it seems reasonable to assume we can consider this issue closed.
