### ISSUE TITLE
v1.7: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2730]
## Planning
- [x] Kick-off notes (private link): _2024-02-13_
- [ ] Create milestone
- [x] Create roadmap issue
- [ ] Pre-release changelog review
- [ ] Create planned changes issues
- [ ] Create issues for:
    - [ ] Updating Docker tags
    - [ ] Updating Postman
    - [ ] Telemetry updates
    - [ ] Code sample tracker
- [ ] Create staging PR

## Implementation: 2024-02-26 — 2024-01-11
- [ ] All PRs created and reviews requested: _2024-03-04_
- [ ] Send final list of code samples sent to @meilisearch/integration-team: _2024-03-05_
- [ ] All PRs approved
- [ ] Final changelog review

## Deploy: _2024-03-11_
- [ ] Merge staging PR into main
- [ ] Notify #ms-releases (private slack channel) once documentation is live
- [ ] Tag the merge commit
- [ ] Close milestone

---

**Scheduled release date:** _2024-03-11_
