### ISSUE TITLE
v1.7: Stabilize `scoreDetails`

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2735]
v1.7 stabilizes `scoreRankingDetails`. The feature is no longer gated behind an experimental feature. To activate it, users must set the search parameter `showRankingScoreDetails` to `true`.

## Questions
- what happens if a user sets `showRankingScore` to `false` and `showRankingScoreDetails` to `true`?

## Tasks
- [ ] Remove `/learn/experimental/ranking_rule_score_details`
- [ ] Set up redirect for removed page pointing to search parameters page
- [ ] Update `/reference/api/search`

## References
- SME: @dureuill 
- engine issue: https://github.com/meilisearch/meilisearch/issues/4359

**Comment by dureuill** [comment]
Hello :wave:

> what happens if a user sets showRankingScore to false and showRankingScoreDetails to true?

they will see the `_rankingScoreDetails`, but not the `_rankingScore`.

Both of these can be displayed or hidden independently.
