### ISSUE TITLE
v1.8: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2791]
## Planning
- [ ] Kick-off notes (private link): https://www.notion.so/meilisearch/v1-8-0-Meilisearch-release-sync-7982cef2721b42219517d2b97ac3d447
- [ ] Create milestone
- [ ] Create roadmap issue
- [ ] Pre-release changelog review
- [ ] Create planned changes issues
- [ ] Create issues for:
    - [ ] Updating Docker tags
    - [ ] Updating Postman
    - [ ] Telemetry updates
    - [ ] Code sample tracker
- [ ] Create staging PR

## Implementation: 2024-04-15 — 2024-05-06
- [ ] All PRs created and reviews requested: _2024-04-18_
- [ ] Send final list of code samples sent to @meilisearch/integration-team: _2024-04-19_
- [ ] All PRs approved
- [ ] Final changelog review

## Deploy
- [ ] Merge staging PR into main
- [ ] Notify #ms-releases (private slack channel) once documentation is live
- [ ] Tag the merge commit
- [ ] Close milestone

---

**Scheduled release date:** _2024-05-06_
