### ISSUE TITLE
v1.8: Limit number of concurrent search requests

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2797]
v1.8 introduces a  limit of 1000 concurrent search requests. The main goal is to protect instances from DoS-style attacks.

Although the limit itself is active by default in all installs, it is possible to configure it with an experimental instance option, `--experimental-search-queue-size`.

## Tasks
- [ ] Create new experimental page
- [ ] Update experimental overview with new feature
- [ ] Update "Known limitations" page

## References
- engine issue: https://github.com/meilisearch/meilisearch/issues/4489
- PRD: https://meilisearch.notion.site/API-usage-of-the-search-limiter-c1edc092f3c746d6899c5ba7bfa9a6a8
- SME: @irevoire
