### ISSUE TITLE
Algolia migration guide improvement

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#2822]
On an [issue](https://github.com/meilisearch/devrel/issues/353#issuecomment-2098202453) in the devrel repo, a user mentioned the following points:

> It would be nice to mention that page in algolia starts from 0 and in meili from 1. Furthermore, attributesToSnippet doesn't exist and there is no mention of forwarding client IP for analytics using X-Forwarded-For for when our client is proxied by our own backend for frontend.

**Comment by guimachiavelli** [comment]
## Tasks

- [ ] Review Algolia migration guide (https://www.meilisearch.com/docs/learn/update_and_migration/algolia_migration)
  - [ ] Add `page` parameter (present in both, starts from `0` in Algolia, `1` in Meilisearch)
  - [ ] Add `attributesToSnippet` (Algolia only, no direct equivalent)

Not sure about the user's last point. XFF is not specific to Meilisearch nor Algolia.

**Comment by CaroFG** [comment]
I think `attributesToSnippet` corresponds to `attributesToCrop`
