### ISSUE TITLE
Reference for actions that cause Meilisearch to reindex indexes

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2831]
Many actions, such as updating index settings and adding new documents, trigger reindexing. These are usually documented with other features, but we should also have a dedicated and comprehensive list for our own reference.

We might want to make that list available for users too, but the first step is to build it internally.

## Tasks

- [ ] contact engine team to see which operations outside of index settings cause reindexings
  - [ ] if there are many operations outside index settings updates, create a reference page with all of them
  - [ ] otherwise mention it in settings reference
- [ ] possibly update the index best practices page
