### ISSUE TITLE
v1.9: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2849]
## Planning
- [x] Kick-off notes (private link): https://www.notion.so/meilisearch/v1-9-0-Meilisearch-release-sync-9a8d3d7536a84fdaa710fcea9fce0b16
- [x] Create milestone
- [x] Create roadmap issue
- [x] Pre-release changelog review
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Telemetry updates
    - [x] Code sample tracker
- [x] Create staging PR

## Implementation: 2024-06-12 — 2024-06-27
- [x] All PRs created and reviews requested: _2024-06-21_
- [x] Send final list of code samples sent to @meilisearch/integration-team: _2024-06-21_
- [x] All PRs approved

## Deploy
- [x] Merge staging PR into main
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit
- [x] Close milestone

---

**Scheduled release date:** _2024-07-01_
