### ISSUE TITLE
Update redirects file

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2919]
@Strift found out we have a few URLs coming from external websites that are pointing to non-existent pages not covered in our redirects.

We need to add those URLs to the redirects file and point them to adequate equivalent/similar pages.

## Tasks

- [x] /docs/reference/features/installation.html#download-and-launch
- [x] /docs/learn/advanced/filtering
- [x] /docs/learn/what_is_meilisearch/contact.html
- [x] /docs/learn/security/tenant_tokens
- [x] /docs/learn/what_is_meilisearch/sdks.html
- [x] /docs/learn/getting_started/a
- [ ] /docs/reference/api/tasks.html#delete-task
