### ISSUE TITLE
v1.10: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2930]
## Planning
- [x] Kick-off notes (private link): https://www.notion.so/meilisearch/v1-10-0-Meilisearch-release-sync-4eb621a9e86f4a369d1f4e80cde9f6ab
- [x] Create milestone
- [x] Create roadmap issue
- [x] Pre-release changelog review
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Telemetry updates
    - [x] Code sample tracker
- [x] Create staging PR

## Implementation: 2024-08-05 — 2024-08-14
- [x] All PRs created and reviews requested: _2024-08-12_
- [x] Send final list of code samples sent to @meilisearch/integration-team: _2024-08-14_
- [x] All PRs approved

## Deploy
- [x] Merge staging PR into main
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit
- [x] Close milestone

---

**Scheduled release date:** _2024-08-26_
