### ISSUE TITLE
v1.11: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2983]
## Planning
- [x] Create milestone
- [x] Create roadmap issue
- [x] Changelog review: https://github.com/meilisearch/engine-team/pull/72/files
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Telemetry updates
    - [x] Code sample tracker
- [x] Create staging PR

## Implementation: 2024-09-23 — 2024-10-17
- [x] All PRs created and reviews requested: _2024-10-10_
- [x] Send final list of code samples sent to @meilisearch/integration-team: _2024-10-10_
- [x] All PRs approved 2024-10-17

## Deploy
- [x] Merge staging PR into main
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit
- [x] Close milestone

---

**Scheduled release date:** _2024-10-28_
