### ISSUE TITLE
v1.12: Roadmap

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#3060]
## Planning
- [x] Create milestone
- [x] Create roadmap issue
- [x] Changelog review: https://github.com/meilisearch/engine-team/pull/73
- [x] Create planned changes issues
- [x] Create issues for:
    - [x] Updating Docker tags
    - [x] Updating Postman
    - [x] Telemetry updates
    - [x] Code sample tracker
- [x] Create staging PR #3068

## Implementation: 2024-12-02 — 2024-12-19
- [x] All PRs created and reviews requested: _2024-12-11_
- [x] Send final list of code samples sent to @meilisearch/integration-team: _2024-12-11_
- [x] All PRs approved 2024-12-17

## Deploy
- [x] Merge staging PR into main
- [x] Notify #ms-releases (private slack channel) once documentation is live
- [x] Tag the merge commit
- [x] Close milestone

---

**Scheduled release date:** _2024-12-23_
