### ISSUE TITLE
v1.12: New `/batches` API route

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#3061]
v1.12 introduces the `/batches` route. Its main goal is to give more information on how tasks are being processed and helps diagnose in case of failure.

- new `GET` `/batches` 
    - supports a several parameters
    - need defaults from #person/tamo
    - returns a list of `batchObjects`
- new `GET` `/batches/:uid` 
    - does not accept query/body parameters
    - returns a single `batchObject`
- updated `/tasks` and `/tasks/:uid`
    - new parameter `batchUids`, returns all tasks whose `batchUid` match the specified value
- updated task object
    - includes new field `batchUid`
- new error: `InvalidBatchUids` for `/batch` and `/batch/:uid`

## Tasks
- [x] Create new `reference/api/batches.mdx`
- [x] Update `reference/api/tasks.mdx`
- [x] Update `learn/async/filtering_tasks.mdx` -> probably add batches to title and/or a box saying everything there is valid for batches
- [x] Update `learn/async/paginating_tasks.mdx` -> same as above
- [x] Update `learn/async/asynchronous_operations.mdx` -> mention batches

## References
- issue on core: https://github.com/meilisearch/meilisearch/issues/4977
- PRD (private link): https://www.notion.so/meilisearch/Enhance-visibility-on-batched-tasks-1194b06b651f810b8fe0fab5d72846a8?pvs=4
- SME: @irevoire
