### ISSUE TITLE
v1.12: New index settings: `prefixSearch` and `facetSearch`

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#3063]
v1.12 introduces two new settings to opt-out of features that affect indexing speed. Essentially, users skip specific indexing subprocesses, exchanging functionality/relevancy for more indexing speed. The concept is more or less the same as `proximityPrecision`.

Setting `facetSearch` to `false` disables all functionality related to the `/facet-search` route.

Setting `prefix` to `disabled` will significantly impact search result relevancy in many/most common scenarios. In short, searching for `he` will only return results matching that string and ignore terms like  `hello`, `head`, and `health`.

- `facetSearch`
      - `{ facetSearch: true | false }`
      - `PATCH /indexes/{index_uid}/settings` -> update via global settings route
      - `PUT /indexes/{index_uid}/settings/facet-search` -> update via dedicated subroute
      - `DELETE /indexes/{index_uid}/settings/facet-search` -> reset
- `prefixSearch`
      - `PATCH /indexes/{index_uid}/settings` -> update via global settings route
      - `PUT /indexes/{index_uid}/settings/prefix-search` -> update via dedicated subroute
      - `DELETE /indexes/{index_uid}/settings/prefix-search` -> reset
      - `{ prefixSearch: "disabled" | "indexingTime" }`
        - `disabled` disables prefix search
        - `indexingTime` is the default behaviour, with Meilisearch calculating prefixes during indexing
- new errors:
    - `facet_search_disabled`
        - triggered when hitting `/facet-search` with `facetSearch` set to `false`
    - `invalid_settings_facet_search`
    - `invalid_settings_prefix_search`

## Tasks
- [x] Update `/reference/api/settings.mdx`
  - [x] Create "Prefix search" section after "Proximity precision"
  - [x] Create "Facet search" section after "Proximity precision"
- [x] Update `/reference/errors/error_codes`

## References
- engine issue: https://github.com/meilisearch/meilisearch/issues/4979
- PRD (private link): https://www.notion.so/meilisearch/API-usage-Settings-to-opt-out-indexing-features-fff4b06b651f8108ade3f858aeb16b14?pvs=4#13d4b06b651f80809121eacf26570f9c
- SME: @ManyTheFish
