### ISSUE TITLE
Tracker: Documentation Restructure

### ISSUE THREAD

**Issue by react-learner** [meilisearch/documentation#619]
Working on a big reorganization of our documentation to make it more consistent, browsable, and extendable. This should have a relatively low impact on content.

Detailed proposal: #634 

Work began: 18 January
Estimated completion: 1 February

- [x] Move and rename .md files within the file hierarchy
- [x] Fix navbar and sidebars (update paths in config.js)
- [x] Rewrite main landing page
- [x] Write landing pages for new sections
- [x] Adjust content to better fit within the new structure (may involve creating new pages / splitting some existing pages)
- [ ] Update all links
- [ ] Open PRs to fix links to documentation links in website and other READMEs

**Comment by fharper** [comment]
This will be @react-learner primary focus for the next week or two!
