### ISSUE TITLE
Tracker: Improve Installation Guide

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#712]
Main tasks:
- [ ] Add the SDKs
- [x] Add DevOps integrations (#620 )
- [x] Expand updating guide – add step-by-step, incl. how to create and import dumps
  - [ ] add specific cloud deploy instructions (#832  )
- [ ] Kubernetes?
- [ ] Platform.sh?

Small tasks:
- [x] Add info: better to compile for performance (#346 )
- [x] Add warning: may not compile on M1 Macs
- [x] Add PC-related warnings (#660 )

This task will be prioritized after docs restructure #619 has completed.

**Comment by maryamsulemani97** [comment]
@dichotommy, is this needed?

**Comment by dichotommy** [comment]
Nope, closing it.

But, I will open an issue about https://github.com/meilisearch/documentation/issues/832 (linked above). I don't think that ever got done; it was [converted to a discussion](https://github.com/meilisearch/documentation/discussions/1267) at some point based on having the `discussion` label 😐
