### ISSUE TITLE
Master branches to Main tracker

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#785]
list of all our public repos: the one checked are already on main as the principal branch instead of master.

- [ ] akamai-purge
- [ ] chiquitita
- [x] cloud-scripts
- [x] demo-MoMA
- [x] devrel
- [x] docs-scraper
- [x] docs-searchbar.js
- [ ] documentation
- [x] finding-crates
- [x] finding-pypi
- [x] finding-rubygems
- [x] github-issues-scraper
- [x] instant-meilisearch
- [x] integration-guides
- [x] madness
- [x] MeiliES
- [x] MeiliSearch
- [x] meilisearch-angular
- [x] meilisearch-aws
- [x] meilisearch-dart
- [x] meilisearch-digitalocean
- [x] meilisearch-dotnet
- [x] meilisearch-go
- [x] meilisearch-java
- [x] meilisearch-js
- [x] meilisearch-kubernetes
- [x] meilisearch-laravel-scout
- [x] meilisearch-php
- [x] meilisearch-postman
- [x] meilisearch-python
- [x] meilisearch-rails
- [x] meilisearch-react
- [x] meilisearch-ruby
- [x] meilisearch-rust
- [x] meilisearch-swift
- [x] meilisearch-symfony
- [x] meilisearch-vue
- [x] meilisearch-wordpress
- [x] searchbar.js
- [ ] serve-rs
- [x] specifications
- [x] strapi-plugin-meilisearch
- [x] Tokenizer
- [x] vuepress-plugin-meilisearch

**Comment by maryamsulemani97** [comment]
@dichotommy, are we still using this?

**Comment by guimachiavelli** [comment]
Not sure why this tracker is on the docs repo, as it goes way beyond our scope. 

Closing this in favour of #1270.
